#!/bin/sh

### BEGIN INIT INFO
# Provides:        radio
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start NTP daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON="/opt/radio/player.py"
DAEMON_USER=root
DAEMON_NAME=radio
PIDFILE="/var/run/$DAEMON_NAME.pid"


do_start() {
        echo "Starting radio"
        #start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --user
        start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON
        log_end_msg $?
}

do_stop() {
    echo "Stopping radio"
        #start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON --user
        start-stop-daemon --stop --pidfile $PIDFILE --retry 10
}

}case "$1" in
    start)
        do_start
        break;;
    stop)
        do_stop
        break;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $DAEMON && exit 0 || exit $?
        break;;
    restart)
        do_stop
        do_start
        break;;
    *)
        echo "Usage: /etc/init.d/radio start|stop|restart|status"
        ;;
esac